CREATE TABLE MOVIE(
 movie_id INTEGER PRIMARY KEY,
 Title VARCHAR2(4000) ,
 IMDBID INTEGER,
Spanish_title VARCHAR2(4000),
 IMBDpicURL VARCHAR2(4000),
 Year INTEGER,
 rtID VARCHAR2(200),
 rtarating INTEGER,
 rtarev INTEGER,
 rtafresh INTEGER,
 rtarotten INTEGER,
 rtaavg INTEGER,
 rttrating INTEGER,
 rttrev INTEGER,
 rttfresh INTEGER,
 rttrotten INTEGER,
rttavg INTEGER,
rtaudirating INTEGER,
rtaudinum INTEGER,
rtaudivg INTEGER,
rtpicurl VARCHAR2(4000)
);

   
CREATE TABLE MOVIE_GENRE(
MovID Int,
Genre Varchar(20),
PRIMARY KEY (MovID,Genre),
FOREIGN KEY (MovID) REFERENCES MOVIE (movie_id)
ON DELETE CASCADE
);

CREATE TABLE MOVIE_ACTOR(
MovID Int,
ACTORID Varchar(50),
ACTORNAME Varchar(50),
Ramking Int,
PRIMARY KEY (MovID,ActorID),
FOREIGN KEY (MovID) REFERENCES MOVIE (movie_id)
ON DELETE CASCADE
);

CREATE TABLE MOVIE_COUNTRY(
MovID Int,
Country Varchar(1000),
PRIMARY KEY (MovID,Country),
FOREIGN KEY (MovID) REFERENCES MOVIE (movie_id)
ON DELETE CASCADE);

CREATE TABLE MOVIE_DIRECTOR(
MovID Int,
DIRECTORID Varchar(1000),
DIRECTORNAME Varchar(1000),
PRIMARY KEY (MovID,DIRECTORID),
FOREIGN KEY (MovID) REFERENCES MOVIE (movie_id)
ON DELETE CASCADE);

CREATE TABLE USER_RATINGS(
USERID Int,
MovID Int,
ratings Int,
date_day Int,
date_month Int,
date_year Int,
date_hour Int,
date_minute Int,
date_second Int,
PRIMARY KEY (USERID,MovID),
FOREIGN KEY (MovID) REFERENCES MOVIE (movie_id)
ON DELETE CASCADE);

CREATE TABLE TAGS(
TagID Int PRIMARY KEY,
Tagtext Varchar(1000)
);


CREATE TABLE MOVIE_TAGS(
TagID Int,
MovID Int,
tagweight Int,
PRIMARY KEY (TagID,MovID)
);

CREATE INDEX gen_inx
ON MOVIE_GENRE(GENRE);

CREATE INDEX country_inx
ON MOVIE_COUNTRY(COUNTRY);

CREATE INDEX act_inx
ON MOVIE_ACTOR(ACTORNAME);

CREATE INDEX dir_inx
ON MOVIE_DIRECTOR (DIRECTORNAME);

CREATE INDEX rat_movyear_inx
ON MOVIE (RTAREV,RTTREV,RTAUDINUM,Year);

CREATE INDEX ur_inx
on USER_RATINGS (USERID,Ratings,DATE_YEAR,DATE_DAY,DATE_MONTH);







