
DROP INDEX gen_inx;
DROP INDEX country_inx;
DROP INDEX act_inx;
DROP INDEX dir_inx;
DROP INDEX rat_movyear_inx;
DROP INDEX ur_inx;

DROP TABLE USER_RATINGS;
DROP TABLE MOVIE_TAGS;
DROP TABLE TAGS;
DROP TABLE MOVIE_COUNTRY;
DROP TABLE MOVIE_GENRE;
DROP TABLE MOVIE_DIRECTOR;
DROP TABLE MOVIE_ACTOR;
DROP TABLE MOVIE;
   